platform :ios, '15.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'

# 禁止所有 Pods 库的警告
inhibit_all_warnings!
use_modular_headers!

# 在你的项目主 Target 中定义依赖
target 'SwiftDemo' do
  # use_frameworks! # 使用动态框架（Swift 库需要）
  pod 'PromiseKit'
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'RxSwift', '~> 6.5'       # 核心库
  pod 'RxCocoa', '~> 6.5'       # UI 扩展
  pod 'RxRelay', '~> 6.5'       # Relay 类型
  pod 'RxDataSources', '~> 5.0' # 列表数据源
  pod 'RxAlamofire', '~> 6.1'   # 网络请求
  pod 'Protobuf'                # Google Protocol Buffer library
  pod 'SwiftProtobuf'           # Swift Protobuf support
  pod 'CocoaMQTT', '~> 2.1'     # MQTT library for iOS
  pod 'MqttCocoaAsyncSocket'    # Support for CocoaMQTT
  pod 'CombineDataBus', :path => './LocalPods/CombineDataBus' # 本地 Combine 数据总线组件
  pod 'RxDataBus', :path => './LocalPods/RxDataBus'           # 本地 RxSwift 数据总线组件
  pod 'PaymentKit', :path => './LocalPods/PaymentKit'         # 本地支付架构组件
  pod 'DownloadKit', :path => './LocalPods/DownloadKit'       # 本地断点续传组件

  # 为测试目标添加依赖
  target 'SwiftDemoTests' do
    inherit! :search_paths
    # 测试目标继承主目标的依赖
    pod 'PromiseKit'
    pod 'Alamofire'
    pod 'SnapKit'
    pod 'RxSwift', '~> 6.5'       # 核心库
    pod 'RxCocoa', '~> 6.5'       # UI 扩展
    pod 'RxRelay', '~> 6.5'       # Relay 类型
    pod 'RxDataSources', '~> 5.0' # 列表数据源
    pod 'RxAlamofire', '~> 6.1'   # 网络请求
  end

end
